---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.artifact_id }}-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{ values.destination }}