# Implement your post-install deployment tasks here
# -------------------------------------------------


# Leave these as the last tasks in the playbook
- name: post_install tasks complete
  debug:
    msg: "Post-Install tasks completed successfully."
  when:
    - not silent|bool

