apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rhivos-template
  title: Build RHIVOS (Tekton)
  description: Build the Red Hat In-Vehicle OS
  tags:
    - automotive
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - component_id
        - base_domain
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: my-rhivos-build
          ui:field: EntityNamePicker
          maxLength: 23
        description:
          title: Description
          type: string
          description: Help others understand what this build is for.
          default: A cool RHIVOS build
        base_domain:
          title: Base Domain
          type: string
          description: Unique name of the component
          default: cluster-zgzkk.zgzkk.sandbox2007.opentlc.com
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.component_id }}-dev
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.${{ parameters.base_domain }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
