# Implement your pre-install deployment tasks here
# -------------------------------------------------

- name: Determine cluster base domain
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
  register: r_ingress_config
  failed_when: r_ingress_config.resources | length < 1

- name: Register cluster base domain
  set_fact:
    cluster_domain: "{{ r_ingress_config.resources[0].spec.domain }}"

# Leave these as the last tasks in the playbook
- name: pre_install tasks complete
  debug:
    msg: "Pre-Install tasks completed successfully."
  when:
    - not silent|bool

