# Implement your post-install deployment tasks here
# -------------------------------------------------
- name: re-create backstage deployment
  shell: |
    oc delete pod `oc get pods -n backstage | awk '{print $1}' | grep backstage-developer-hub` -n backstage

- name: remove backstage config file
  file:
    path: "../roles/patch_backstage/templates/app-config.yaml"
    state: absent

# Leave these as the last tasks in the playbook
- name: post_install tasks complete
  debug:
    msg: "Post-Install tasks completed successfully."
  when:
    - not silent|bool

